import type { Metadata } from "next";
import "./globals.css";
import { geistMono, geistSans } from "@/fonts/fonts";
import LoadingAnimation from "@/components/LoadingAnimation";

export const metadata: Metadata = {
  title: "Portfolio by Kaif",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistMono.variable} antialiased scroll-smooth bg-background text-foreground [&::-webkit-scrollbar]:w-1.5 [&::-webkit-scrollbar-track]:bg-background [&::-webkit-scrollbar-thumb]:bg-foreground dark:[&::-webkit-scrollbar-track]:bg-background dark:[&::-webkit-scrollbar-thumb]:bg-foreground`}
        suppressHydrationWarning
      >
        <LoadingAnimation>
          <main className="w-full min-h-screen flex">{children}</main>
        </LoadingAnimation>
      </body>
    </html>
  );
}
