import type { Metadata } from "next";
import "./globals.css";
import { geistMono, geistSans } from "@/fonts/fonts";
import { ThemeProvider } from "next-themes";
import LoadingAnimation from "@/components/LoadingAnimation";

export const metadata: Metadata = {
  title: "Portfolio by Kaif",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistMono.className} ${geistSans.variable} antialiased scroll-smooth bg-background text-foreground [&::-webkit-scrollbar]:w-2
  [&::-webkit-scrollbar-track]:bg-background
  [&::-webkit-scrollbar-thumb]:bg-foreground
  dark:[&::-webkit-scrollbar-track]:bg-background
  dark:[&::-webkit-scrollbar-thumb]:bg-foreground`}
        suppressHydrationWarning
      >
        <LoadingAnimation>
          <main className="w-full min-h-screen flex">
            <ThemeProvider>{children}</ThemeProvider>
          </main>
        </LoadingAnimation>
      </body>
    </html>
  );
}
